kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-system-sa-rolebinding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: kube-system-sa
  namespace: kube-system
roleRef:
  kind: Role
  name: kube-system-role
  apiGroup: rbac.authorization.k8s.io
