apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: dvwa-mysql8
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi #64 MB