apiVersion: v1
kind: Service
metadata:
  name: dvwa-php72-service
  labels:
    run: dvwa-php72-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: dvwa-php72