apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa-php72
  labels:
    app: dvwa-php72
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa-php72
  template:
    metadata:
      labels:
        app: dvwa-php72
    spec:
      containers:
      - name: dvwa-php72
        image: localhost:32000/dvwak8s_website:k8s
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
